#Configure Logging
quarkus:
  log:
    level: INFO
    min-level: TRACE
    category:
      "org.gameontext.map":
        level: TRACE
      "org.gameontext.map.auth":
        level: TRACE
      "org.gameontext.map.db":
        level: TRACE
      "org.gameontext.map.filter":
        level: TRACE
      "org.gameontext.map.model":
        level: TRACE
      "org.gameontext.signed":
        level: TRACE        

#Configure root path for quarkus (note, not honored by websocket registrations)
  http:
    root-path: /map
#Configure port to be compatible with previous map service =)
    port: 9080
#Ensure we're listening to all interfaces 
    host: 0.0.0.0    

#Force health to paths compatible with GameOn
    non-application-root-path: ${quarkus.http.root-path}

  smallrye-health:
    root-path: health
    liveness-path: liveness


